### ISSUE TITLE
Checklist for new kits

### ISSUE THREAD

**Issue by snaar** [HaliteChallenge/Halite-III#84]
Thoughts for now:
- [ ] can take own rng seed as first cmd line arg
- [ ] normalization handles negative coordinates
- [ ] instances of ship class are reused between turns as needed
